spring.application.name=api
# K\u1EBFt n\u1ED1i t\u1EDBi MongoDB \u1EDF máy cá nhân (localhost) và t\u1EA1o m\u1ED9t database tên là phongthuy_db
spring.data.mongodb.uri=mongodb://localhost:27017/phongthuy_db
server.port=8081